# Generated by Django 4.2.3 on 2024-07-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="default_role", max_length=200),
        ),
    ]
