# Generated by Django 4.2.3 on 2024-07-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_news_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(
                related_name="news", to="news.category"
            ),
        ),
    ]
